# Generated by Django 5.2 on 2025-04-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CART', 'Cart'), ('ORDERED', 'Order Placed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='CART', max_length=20),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
