# Generated by Django 5.2 on 2025-04-11 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_organic',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_unit',
        ),
    ]
